# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         X3D
version:      0.003
version_from: lib/X3D.pm
installdirs:  site
requires:
    Algorithm::Numerical::Shuffle: 0
    base:                          0
    Benchmark:                     0
    Carp:                          0
    Class::ISA:                    0
    constant:                      0
    Data::Dumper:                  0
    enum:                          0
    Exporter:                      0
    File::Temp:                    0
    Hash::NoRef:                   0
    Inline:                        0
    integer:                       0
    Math::Complex:                 0
    Math::Quaternion:              0
    Math::Trig:                    0
    overload:                      0
    Package::Alias:                0
    POSIX:                         0
    Scalar::Util:                  0
    strict:                        0
    Sub::Name:                     0
    Test::More:                    0
    Tie::Array:                    0
    Tie::Hash:                     0
    Tie::Scalar:                   0
    Time::HiRes:                   0
    Unicode::String:               0
    UNIVERSAL:                     0
    Want:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
